language: minimal

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          update: true
    # - os: osx
    #   osx_image: xcode9.1
    #   before_install:
    #     - brew tap caskroom/cask
    #     - brew cask install powershell
  fast_finish: true

before_install:
  - echo "Pass 01 before_install"

install:
  - echo "Pass 02 install"

before_script:
  - echo "Pass 03 before_script"
  - chmod 755 ./build/*.sh
  # - pwsh -f "${env:TRAVIS_BUILD_DIR}/build.ps1"

script:
  - echo "Pass 04 script"
  # - pwsh -f "${env:TRAVIS_BUILD_DIR}/test.ps1"
  - ${TRAVIS_BUILD_DIR}/build/build-deb.sh -dev -api "${TRAVIS_BUILD_DIR}"

before_cache:
  - echo "Pass 05 before_cache"

after_success:
  - echo "Pass 06 after_success"
  # - pwsh -f "${env:TRAVIS_BUILD_DIR}/deploy.ps1"

after_falure:
  - echo "Pass 06 after_failure"
  # - pwsh -f "${env:TRAVIS_BUILD_DIR}/deploy.ps1"

before_deploy:
  - echo "Pass 07 before_deploy"

# deploy:
#   - echo "Pass 08 deploy"

after_deploy:
  - echo "Pass 09 after_deploy"

after_script:
  - echo "Pass 10 after_script"

